# Generated by Django 5.0.7 on 2026-09-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='purpose',
            field=models.CharField(choices=[('general', 'Umumiy AI'), ('kitchen', 'Oshxona AI'), ('study', "O'qish AI"), ('document', 'Hujjat AI'), ('translation', 'Tarjima AI'), ('home', 'Uy AI'), ('finance', 'Moliya AI'), ('programming', 'Kod AI'), ('ideas', "G'oya AI"), ('cv', 'CV / Ish AI')], default='general', max_length=20),
        ),
    ]
